// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/saga/saga.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SagaService_StartOrderSaga_FullMethodName        = "/saga.SagaService/StartOrderSaga"
	SagaService_GetSagaStatus_FullMethodName         = "/saga.SagaService/GetSagaStatus"
	SagaService_CompensateTransaction_FullMethodName = "/saga.SagaService/CompensateTransaction"
	SagaService_ListSagaTransactions_FullMethodName  = "/saga.SagaService/ListSagaTransactions"
)

// SagaServiceClient is the client API for SagaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SagaService provides distributed transaction management
type SagaServiceClient interface {
	// StartOrderSaga starts a new order saga transaction
	StartOrderSaga(ctx context.Context, in *StartOrderSagaRequest, opts ...grpc.CallOption) (*StartOrderSagaResponse, error)
	// GetSagaStatus retrieves the status of a saga transaction
	GetSagaStatus(ctx context.Context, in *GetSagaStatusRequest, opts ...grpc.CallOption) (*GetSagaStatusResponse, error)
	// CompensateTransaction triggers compensation for a failed transaction
	CompensateTransaction(ctx context.Context, in *CompensateTransactionRequest, opts ...grpc.CallOption) (*CompensateTransactionResponse, error)
	// ListSagaTransactions retrieves a list of saga transactions
	ListSagaTransactions(ctx context.Context, in *ListSagaTransactionsRequest, opts ...grpc.CallOption) (*ListSagaTransactionsResponse, error)
}

type sagaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSagaServiceClient(cc grpc.ClientConnInterface) SagaServiceClient {
	return &sagaServiceClient{cc}
}

func (c *sagaServiceClient) StartOrderSaga(ctx context.Context, in *StartOrderSagaRequest, opts ...grpc.CallOption) (*StartOrderSagaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartOrderSagaResponse)
	err := c.cc.Invoke(ctx, SagaService_StartOrderSaga_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sagaServiceClient) GetSagaStatus(ctx context.Context, in *GetSagaStatusRequest, opts ...grpc.CallOption) (*GetSagaStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSagaStatusResponse)
	err := c.cc.Invoke(ctx, SagaService_GetSagaStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sagaServiceClient) CompensateTransaction(ctx context.Context, in *CompensateTransactionRequest, opts ...grpc.CallOption) (*CompensateTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompensateTransactionResponse)
	err := c.cc.Invoke(ctx, SagaService_CompensateTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sagaServiceClient) ListSagaTransactions(ctx context.Context, in *ListSagaTransactionsRequest, opts ...grpc.CallOption) (*ListSagaTransactionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSagaTransactionsResponse)
	err := c.cc.Invoke(ctx, SagaService_ListSagaTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SagaServiceServer is the server API for SagaService service.
// All implementations must embed UnimplementedSagaServiceServer
// for forward compatibility.
//
// SagaService provides distributed transaction management
type SagaServiceServer interface {
	// StartOrderSaga starts a new order saga transaction
	StartOrderSaga(context.Context, *StartOrderSagaRequest) (*StartOrderSagaResponse, error)
	// GetSagaStatus retrieves the status of a saga transaction
	GetSagaStatus(context.Context, *GetSagaStatusRequest) (*GetSagaStatusResponse, error)
	// CompensateTransaction triggers compensation for a failed transaction
	CompensateTransaction(context.Context, *CompensateTransactionRequest) (*CompensateTransactionResponse, error)
	// ListSagaTransactions retrieves a list of saga transactions
	ListSagaTransactions(context.Context, *ListSagaTransactionsRequest) (*ListSagaTransactionsResponse, error)
	mustEmbedUnimplementedSagaServiceServer()
}

// UnimplementedSagaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSagaServiceServer struct{}

func (UnimplementedSagaServiceServer) StartOrderSaga(context.Context, *StartOrderSagaRequest) (*StartOrderSagaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartOrderSaga not implemented")
}
func (UnimplementedSagaServiceServer) GetSagaStatus(context.Context, *GetSagaStatusRequest) (*GetSagaStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSagaStatus not implemented")
}
func (UnimplementedSagaServiceServer) CompensateTransaction(context.Context, *CompensateTransactionRequest) (*CompensateTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompensateTransaction not implemented")
}
func (UnimplementedSagaServiceServer) ListSagaTransactions(context.Context, *ListSagaTransactionsRequest) (*ListSagaTransactionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSagaTransactions not implemented")
}
func (UnimplementedSagaServiceServer) mustEmbedUnimplementedSagaServiceServer() {}
func (UnimplementedSagaServiceServer) testEmbeddedByValue()                     {}

// UnsafeSagaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SagaServiceServer will
// result in compilation errors.
type UnsafeSagaServiceServer interface {
	mustEmbedUnimplementedSagaServiceServer()
}

func RegisterSagaServiceServer(s grpc.ServiceRegistrar, srv SagaServiceServer) {
	// If the following call pancis, it indicates UnimplementedSagaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SagaService_ServiceDesc, srv)
}

func _SagaService_StartOrderSaga_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartOrderSagaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SagaServiceServer).StartOrderSaga(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SagaService_StartOrderSaga_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SagaServiceServer).StartOrderSaga(ctx, req.(*StartOrderSagaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SagaService_GetSagaStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSagaStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SagaServiceServer).GetSagaStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SagaService_GetSagaStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SagaServiceServer).GetSagaStatus(ctx, req.(*GetSagaStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SagaService_CompensateTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompensateTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SagaServiceServer).CompensateTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SagaService_CompensateTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SagaServiceServer).CompensateTransaction(ctx, req.(*CompensateTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SagaService_ListSagaTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSagaTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SagaServiceServer).ListSagaTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SagaService_ListSagaTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SagaServiceServer).ListSagaTransactions(ctx, req.(*ListSagaTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SagaService_ServiceDesc is the grpc.ServiceDesc for SagaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SagaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "saga.SagaService",
	HandlerType: (*SagaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartOrderSaga",
			Handler:    _SagaService_StartOrderSaga_Handler,
		},
		{
			MethodName: "GetSagaStatus",
			Handler:    _SagaService_GetSagaStatus_Handler,
		},
		{
			MethodName: "CompensateTransaction",
			Handler:    _SagaService_CompensateTransaction_Handler,
		},
		{
			MethodName: "ListSagaTransactions",
			Handler:    _SagaService_ListSagaTransactions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/saga/saga.proto",
}
