app:
  name: ecommerce-saga
  environment: development
  debug: true

server:
  host: "localhost"
  port: "8080"
  read_timeout: 10s
  write_timeout: 10s

grpc:
  host: "localhost"
  port: 50051

auth:
  jwt:
    key: "your-secret-key"
    expiry: "15m"
  jwk:
    rotation_period: "24h"
    key_size: 2048

database:
  postgres:
    host: "localhost"
    port: "5432"
    user: "postgres"
    password: "postgres"
    dbname: "ecommerce"
    sslmode: "disable"
  mongodb:
    uri: "mongodb://localhost:27017"
    database: "ecommerce"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0

messagebrokers:
  rabbitmq:
    host: "localhost"
    port: "5672"
    user: "guest"
    password: "guest"
    vhost: "/"
    
  kafka:
    brokers:
      - "localhost:9092"
    group_id: "ecommerce-group"
    
  nsq:
    host: "localhost"
    port: "4150"
    
  nats:
    url: "nats://localhost:4222"
    cluster: "test-cluster"

saga:
  timeout: 5m
  retry:
    max_attempts: 3
    initial_interval: 1s
    max_interval: 30s

monitoring:
  prometheus:
    port: 9090
  
  logging:
    level: debug
    format: json 